### ISSUE TITLE
Deprecate hook.hook() and $hook$.nativeAPI

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#148]
Deprecate `hook.hook(PlatformObject)` and `$hook$.nativeAPI`

## Note
- Hook scripts in hook callback function instead

## Tasks
- [ ] `Function('script')`
- [ ] `eval('script')`
- [ ] `setTimeout('script')`
- [ ] `setInterval('script')`
- [ ] `Document.write` for script
- [ ] `Node.textContent` for `<script>script</script>`
- [ ] `HTMLScriptElement.type` for `type="text/javascript"`
- [ ] `HTMLAnchorElement.href` for `href="javascript:..."`
- [ ] `HTMLAreaElement.href` for `href="javascript:..."`
- [ ] `HTMLElement.setAttribute`for `type="text/javascript", href="javascript:...", onXXX="..."`
