### ISSUE TITLE
[demo][acl] Support modules

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#191]
[demo][acl] Support modules

## Tasks (Specs are tentative)
- [ ] Hook modules
  - [ ] `require('module.js')` 
    - [ ] `__hook__(() => require('module.js'), null, [ 'require', 'module.js', '/resolved/module.js'], 'context', NaN)`
  - [ ] `import('module.js')`
  - [ ] `import`
    - [ ] `import from 'module.js'`
    - [ ] More...
  - [ ] `export`
    - [ ] `export * from 'module.js'`
    - [ ] More...
- [ ] Add pre-hooked bundled modules in demo
  - [ ] `require()` context generator for pre-hooked modules
    - [ ] `/base/context/module1.js,x|/target/virtual/context/module.js`
  - [ ] Hook transformer
    - [ ] browserify
    - [ ] webpack
  - [ ] CommonJS - browserify
  - [ ] CommonJS - webpack
  - [ ] ES Module - webpack
- [ ] Hook callback
  - [ ] `require()` handling
    - [ ] Register the object and its methods with its virtual object name
    - [ ] applyAcl
```javascript
const acl = {
    // bundled modules
    '/components/thin-hook/node_modules/xliff-conv/xliff-conv.js': {
      [S_DEFAULT]: 'r-x',
      xliffStates: '---',
    },
    '/components/thin-hook/demo/commonjs2.js': {
      [S_DEFAULT]: 'r--', // add() is not executable
    },
    '/components/thin-hook/node_modules/path-browserify/index.js': {
      [S_DEFAULT]: 'r-x',
      join: {
        [S_DEFAULT]: '--x',
        '@path_join_prohibited': '---',
      },
    },
}
```
  - [ ] `import()` handling
    - [ ] Register the object and its methods with its virtual object name
      - Note: How to handle asynchronous objects?
    - [ ] applyAcl
  - [ ] `import` handling
    - [ ] TBD
  - [ ] `export` handling
    - [ ] TBD

**Comment by t2ym** [comment]
## Note
- The entry module should be registered as a global variable, which can be handled in ACL.

**Comment by t2ym** [comment]
## Context generator for bundler

```javascript
const browserifyBuiltins = require('browserify/lib/builtins.js');
const nodeLibsBrowser = require('node-libs-browser');

const urlForCurrendDir = '/components/thin-hook';

function bundlerContextGeneratorFactory(nodeLibs) {
  return function requireContextGenerator(astPath) {
    let ast = astPath[astPath.length - 1][1];
    let context = hook.contextGenerators.method(astPath);
    if (ast.type === 'CallExpression' &&
        ast.callee.type === 'Identifier' &&
        ast.callee.name === 'require' &&
        ast.arguments.length === 1 &&
        ast.arguments[0].type === 'Literal' &&
        typeof ast.arguments[0].value === 'string') {
      let name = ast.arguments[0].value;
      let origin = context.split(/,/)[0];
      let cwd = process.cwd();
      let originUrlDir = path.dirname(origin);
      let originPhysicalDir = cwd + originUrlDir.substring(urlForCurrendDir.length);
      let adjustedName = name;
      let resolved;
      let componentPath;
      let componentName;
      if (name[0] === '.') {
        adjustedName = path.join(originPhysicalDir, name);
        resolved = require.resolve(adjustedName);
        componentPath = resolved.substring(cwd.length);
      }
      else {
        resolved = nodeLibs[name];
        if (resolved) {
          componentPath = resolved.substring(cwd.length);
        }
        else {
          resolved = require.resolve(name);
          componentPath = resolved.substring(cwd.length);
        }
      }
      componentName = urlForCurrendDir + componentPath;
      console.log('requireContextGenerator: context = ' + context + ' name = ' + name + ' componentName = ' + componentName);
      context += '|' + componentName;
    }
    return context;
  };
}

hook.contextGenerators.webpack = bundlerContextGeneratorFactory(nodeLibsBrowser);
hook.contextGenerators.browserify = bundlerContextGeneratorFactory(browserifyBuiltins);

```

**Comment by t2ym** [comment]
## Hook transformer for bundlers
- Applied to both browserify and webpack
```javascript
// Hook transformer - browserify transform
function hookTransformFactory(contextGeneratorName) {
  return function hookTransform(file) {
    let cwd = process.cwd();
    let chunks = [];
    function transform(chunk, encoding, callback) {
      chunks.push(chunk);
      callback();
    }
    function flush(callback) {
      let stream = this;
      let code = Buffer.concat(chunks).toString();
      let context =
        //file.substring(cwd.length); // based on the build path
        urlForCurrendDir + file.substring(cwd.length); // based on the polyserve path mapping without --npm option
      if (!file.match(/\/node_modules\/webpack\/buildin\/module[.]js$/)) { // TODO: Hooking webpack/buildin/module.js raises an error
        code = hook(code,
          '__hook__', // hookName = '__hook__',
          [ [ context, {} ] ], // initialContext = [],
          contextGeneratorName, // contextGeneratorName = 'method',
          true, // metaHooking = true,
          true, // _hookProperty = getHookProperty(),
          null, // _sourceMap = null,
          false, // asynchronous = false,
          false, // _compact = getCompact(),
          true, // _hookGlobal = getHookGlobal(),
          '_pp_', // _hookPrefix = getHookPrefix(),
          { require: true, module: true, exports: true } // initialScope = null
        );
      }
      console.log('hook ', file);
      stream.push(code);
      callback(null);
    }
    return through(transform, flush);
  }
}
```

**Comment by t2ym** [comment]
## Gulp tasks for bundlers

### CommonJS modules by browserify
```javascript
// Hook CommonJs modules in browserify
// NOTES:
// - Wrappers are not hooked
gulp.task('browserify-commonjs', () => {
  const cwd = process.cwd();
  return browserify('./demo/commonjs.js', { standalone: 'commonjs_module', insertGlobals: false, insertGlobalVars: {
      __hook__: undefined
    } })
    .transform({ global: true }, hookTransformFactory('browserify'))
    .bundle()
    .pipe(source('browserify-commonjs.js'))
    .pipe(buffer())
    .pipe(gulp.dest('./demo'));

});
```

### CommonJs modules by webpack
```javascript
// Hook CommonJs modules in webpack
// NOTES:
// - Wrappers like __webpack_require__ are not hooked
gulp.task('webpack-commonjs', () => {
  const cwd = process.cwd();
  const webpackConfig = {
    entry: "./demo/commonjs.js",
    output: {
      filename: "webpack-commonjs.js"
    },
    plugins: [
      new webpack.LoaderOptionsPlugin({
        options: {
          transforms: [
            hookTransformFactory('webpack')
          ]
        }
      })
    ],
    module: {
      loaders: [{
        test: /\.js$/,
        loader: 'transform-loader?0',
      }],
    },
  };
  return webpackStream(webpackConfig, webpack)
    .pipe(gulp.dest('./demo'));

});

```

### ES6 Modules by webpack
```javascript
// Hook ES6 modules in webpack
// NOTES:
// - Wrappers like __webpack_require__ are not hooked
gulp.task('webpack-es6-module', () => {
  const cwd = process.cwd();
  const webpackConfig = {
    entry: "./demo/es6-module3.js",
    output: {
      filename: "webpack-es6-module.js"
    },
    plugins: [
      new webpack.LoaderOptionsPlugin({
        options: {
          transforms: [
            hookTransformFactory('webpack')
          ]
        }
      })
    ],
    module: {
      loaders: [{
        test: /\.js$/,
        loader: 'transform-loader?0',
      }],
    },
  };
  return webpackStream(webpackConfig, webpack)
    .pipe(gulp.dest('./demo'));
});
```

**Comment by t2ym** [comment]
## ES Module Policy Patterns (draft 1)
<img src="https://raw.githubusercontent.com/wiki/t2ym/thin-hook/module-policies-draft-1.png" width="11810px">

**Comment by t2ym** [comment]
## Extended and Exported Classes must be handled properly
- [ ] TODO: What is the proper handling?

```js
// module-for-base-class.js
export class C { static sm(){} m(){} }
export const baseObj = { p: v };
```
```js
// module-for-extended-class.js
import { C, baseObj } from "./module-for-base-class.js";
export class E extends C { static s(){} m(){} }
export const extendedObj = Object.assign(Object.create(baseObj), { p2: v2 });
```

<img src="https://raw.githubusercontent.com/wiki/t2ym/thin-hook/object-chain-1.svg?sanitize=true">

### Note: SVG source code for [`http://www.webgraphviz.com/`](http://www.webgraphviz.com/)
```
digraph finite_state_machine {
        rankdir=UD;
	ratio = fill;
	node [style=filled fontsize=12];
"Object" [color=lightblue]
"Function" [color=lightblue]
"class C { static sm(){} m(){} }" [color=lightblue]
"class E extends C { static s(){} m(){} }" [color=lightblue]
"Object.prototype" [color=lightgreen]
"Function.prototype" [color=lightgreen]
"C.prototype" [color=lightgreen]
"E.prototype" [color=lightgreen]

"Object" -> "Function.prototype" [label="__proto__"]
"Object" -> "Object.prototype" [color="0.348 0.839 0.839"  label = "prototype" ]
"Object.prototype" -> "Object" [label = "constructor" ]
"Object.prototype" -> "Object.prototype.hasOwnProperty()" [label="hasOwnProperty"]
"Object.prototype.hasOwnProperty()" -> "Function.prototype"  [color="0.650 0.700 0.700" label = "__proto__" ]
"Object" -> "Object.create()" [label="create"]
"Object.create()" -> "Function.prototype"  [color="0.650 0.700 0.700" label = "__proto__" ]
"{p:v}" -> "Object.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"{p:v}" -> "v" [label="p"]
"{p2:v2}" -> "{p:v}" [color="0.650 0.700 0.700" label = "__proto__" ]
"{p2:v2}" -> "v2" [label="p2"]
"{p3:v3}" -> "null" [color="0.650 0.700 0.700" label = "__proto__" ]
"{p3:v3}" -> "v3" [label="p3"]
"Function" -> "Function.prototype" [color="0.348 0.839 0.839"  label = "prototype" ]
"function f(){}" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"()=>{}" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"class C { static sm(){} m(){} }" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"class C { static sm(){} m(){} }" -> "C.prototype" [color="0.348 0.839 0.839" label = "prototype" ]
"class C { static sm(){} m(){} }" -> "C.sm()" [label = "sm" ]
"C.sm()" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"C.prototype.m()" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"C.prototype" -> "class C { static sm(){} m(){} }" [label = "constructor" ]
"C.prototype" -> "C.prototype.m()" [label = "m" ]
"C.prototype" -> "Object.prototype" [color="0.650 0.700 0.700" label="__proto__"]
"class E extends C { static s(){} m(){} }" -> "class C { static sm(){} m(){} }" [color="0.650 0.700 0.700" label = "__proto__" ]
"class E extends C { static s(){} m(){} }" -> "E.prototype" [color="0.348 0.839 0.839"  label = "prototype" ]
"class E extends C { static s(){} m(){} }" -> "E.s()" [label = "s" ]
"E.prototype.m()" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"E.s()" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"E.prototype" -> "E.prototype.m()" [label = "m" ]
"new C()" -> "C.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"new C()" -> "value" [label="instanceProperty"]
"new E()" -> "E.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"new E()" -> "value2" [label="instanceProperty"]
"E.prototype" -> "class E extends C { static s(){} m(){} }" [label = "constructor" ]
"E.prototype" -> "C.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"Function" -> "Function.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
"Function.prototype" -> "Function" [label = "constructor" ]
"Function.prototype" -> "Object.prototype" [color="0.650 0.700 0.700" label = "__proto__" ]
}
```

**Comment by t2ym** [comment]
# [DIGRESSION]
### At the time of this posting, my fatigue has accumulated like this:

<img src="https://raw.githubusercontent.com/wiki/t2ym/thin-hook/PC-8001_mon_TM.gif">

### I need some time to clear work areas in my mind and find consistent and performant schema for ES module support as my mind is messed like this:

<img src="https://raw.githubusercontent.com/wiki/t2ym/thin-hook/PC-8001_EDAS_VRAM_mess.gif">

### As you have just realized from this digression post, I am steadily recovering from the fatigue

### I hope you wait for updates

### Notes
- These screenshots are powered by 
  - [j80 emulator](http://upd780c1.g1.xrea.com/pc-8001/index.html)
  - Extracted ROM images from PC-8001 equipped with the EDAS ROM via CMT I/F and mic input
  - [peek recorder](https://github.com/phw/peek)
- While I was migrating to a new PC, I happened to find the old j80 archive that I had briefly played long ago just for nostalgia 
- With OpenJDK 1.8 on Ubuntu, j80 hangs once any pull down menu is accessed. It seems j80 fails to handle menu events. (I have no intention and time to solve the issue)
