### ISSUE TITLE
Support import.meta

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#225]
Support `import.meta`

## Tasks
- [ ] Parse `import.meta`
- [ ] Hook `import.meta`
- [ ] Apply ACL for `import.meta` and `import.meta.url`

**Comment by t2ym** [comment]
## Hooked `import.meta`
```javascript
__hook__(() => import.meta, null, ['import.meta'], 'context', NaN)
```
### Notes
- Hooked as a wrapper function `() => import.meta` with a dummy argument `('import.meta')`
- This hooking method may look strange but is upper compatible with current hook callbacks, which just pass `import.meta` without blocking.

**Comment by t2ym** [comment]
## Change on `t2ym/espree` to parse `import.meta`
https://github.com/t2ym/espree/commit/2c936c906c2b20cd06c125f01d86a4ce85ba6e12

**Comment by t2ym** [comment]
# Notes
- This fix does NOT patch `import.meta.url` as a literal string for the imported URL of the module.

**Comment by t2ym** [comment]
Change for demo ACL
https://github.com/t2ym/thin-hook/commit/7d2f0468cd674ae410a9f2ba822a938d13363ea7
