### ISSUE TITLE
[README][HTML Imports] Update documentation for HTML Imports polyfill support

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#295]
[README][HTML Imports] Update documentation for HTML Imports polyfill support #275 

## TODOs
- [ ] README on `demo/script-hashes.js`
- [ ] README on `demo/content-loader.js`
- [ ] On `gulp script-hashes`
- TBD
