### ISSUE TITLE
Consideration on production front-end build processes

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#73]
#### For hook target modules
1. Load hook target modules
2. Hook the modules (`hook()`, `hook.hookHtml()` with an appropriate context generator)
3. Bundle the hooked modules by webpack, rollup, browserify, vulcanize, polymer-bundler, etc.
4. Add the hooked bundle to the no-hook list (Adding a `pre-hook` list may be better to avoid confusion)
#### For no-hook modules
1. Load no-hook modules
2. Bundle context-generator modules into a single context-generator module
3. Bundle non-context-generator modules into a single no-hook module

#### Combination of build-time and run-time hooking
1. Load the encoded entry HTML page
2. Load `hook.min.js`
3. Register the Service Worker
4. Load the decoded entry HTML page
5. Load the context-generator bundled module
6. Load the no-hook bundled module
7. Load the hooked bundle as a no-hook (or pre-hook) module
8. Load other hook target modules with run-time hooking
#### Eliminate run-time hooking and the Service Worker
1. Load the pre-decoded entry HTML page without Service Worker
2. Load the context-generator bundled module
3. Load the no-hook bundled module
4. Load the hooked bundle as a no-hook (or pre-hook) module
5. Load no more modules at run-time

### Notes
- The no-hook bundled module can be merged into the hooked bundle
- Sharding into multiple bundle modules is optional for progressive web applications

### Tasks
- [ ] Gulp task to pre-hook modules
- [ ] Flexible and seamless integration with various bundlers
  - [ ] Webpack
  - [ ] Rollup
  - [ ] Browserify
  - [ ] Vulcanize
  - [ ] Polymer-bundler
  - [ ] More...
- [ ] Generation of policies for the hook callback
