### ISSUE TITLE
Hook global variables

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#85]
# Hook global variables

## Targets
- global `var`, `function`, `let`, `const`, `class` declarations
- global variable access without member expressions
  - Note: Member expression can be hooked via `hook-property` option

## Tasks
- [x] Analyze Variable Scopes ((nested) block / (nested) function / module / global / class global)
- [x] Define `hook.global(__hook__, 'context', 'globalVariableName', 'var|function|let|const|class|get|set|delete')` hook function
  - [x] Proper emulation of already defined error
  - [x] Constant variables cannot be changed
- [x] Hook global variable declarations (`var`, `let`, `const`) with the hook function
  - [x] Simple variable declarations (`var g1, g2;`)
  - [x] Initialized variable declarations (`var g1 = 1, g2 = 'a';`)
  - [x] Initialized variable declarations with Array destructuring (`var [ a, b ] = [ 'va', 'vb' ];`)
  - [x] Initialized variable declarations with nested Array destructuring (`var [ a, [ b ] ] = [ 'va', [ 'vb' ] ];`)
  - [x] Initialized variable declarations with rest element (`var [a, ...b] = ['va', 'vb1', 'vb2']`)
  - [x] Initialized variable declarations with Array rest element (`var [a, ...[b1, b2] = ['va', 'vb1', 'vb2']`)
  - [x] Initialized variable declarations with Object destructuring (`var { a: x, b: y } = { a: 1, b: 2 };`)
  - [x] Initialized variable declarations with Object destructuring for shorthand property (`var { a, b } = { a: 1, b: 2 };`)
  - [x] Initialized variable declarations with nested Object destructuring (`var { a: x, p: { b: y } } = { a: 1, p: { b: 2 } };`)
  - [x] Initialized variable declarations with Array destructuring with default values (`var [ a, b = 1 ] = [ 'va' ];`)
  - [x] Initialized variable declarations with Object destructuring with default values (`var { a: x, b: y = 3 } = { a: 1 };`)
  - [ ] ...
- [x] Hook global function declarations (`function`) with the hook function
- [x] Hook global class declarations (`class`) with the hook function
- [x] Hook implicit global variable creation and assignment (`g = value`) with the hook function
- [x] Hook global object assignments with Array destructuring (`[ a, b ] = [ 'va', 'vb' ];`)
  - [x] Flat
  - [x] Nested
- [x] Hook global object assignments with Object destructuring (`({ a: x, b:y } = { a: 'vx', b: 'vy' });`)
  - [x] Flat
  - [x] Nested
- [x] Hook global variable operations (analysis in progress)
  - [x] UpdateOperation (`++`, `--`)
  - [x] Assignments (`+=`, `-=`, ...)
  - [x] More...
- [x] Hook global function calls (e.g., `addEventListener(...)`) with the hook function
- [x] Hook delete operation of global variable with the hook function (`delete gVar`)
- [x] Provide hooked `eval()` script with its local scope
- [x] Add `hook-global=true|false` option (enabled when `hook-property=true` is also enabled)
- [x] Add `hook-prefix=_p_` option to prefix proxy accessors
- [x] Hook global object references excluding member expressions (analysis in progress)
  - [x] Assignments (RHS) (`x = gobject;`)
  - [x] Assignments (LHS)
- [ ] Performance Optimization

## Notes
- Global `let`, `const`, `class` declarations are not bound to the global object by default (without hooking) but bound to the inaccessible global class scope object (closure)
- Hooked global `let`, `const`, `class` declarations have to be bound to the global object
  - There are no handy (high performance) way of accessing hooked version of the variables
  - Global `let`, `const`, `class` declarations in no-hook scripts are discouraged as they are uncontrollable
  - Behaviors of global `let`, `const`, `class` declarations have to be emulated by global variables with `hook.global()` hook function

## Known Issues
- Should function declarations in a block be block-scoped (for strict mode)?
- Should `export { unexpectedGlobalVar as X }` be replaced with `export { undefined as X }`?
- Global `undefined` is hooked 
- Overriding a `const` variable does not throw an error, but the new value is silently discarded.

**Comment by t2ym** [comment]
Close it as global hooking is becoming mature.  Other issues will be handled separately.
